.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. lipcoin_qt test_lipcoin_qt
clean: FORCE
	$(MAKE) -C .. lipcoin_qt_clean test_lipcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_lipcoin_qt_check
lipcoin-qt lipcoin-qt.exe: FORCE
	 $(MAKE) -C .. lipcoin_qt
